# -*- coding: utf-8 -*-
"""Bland-Altman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGe-PcLt9LnaUWkiqf-Y3AA7hXOhHJ8h
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import chardet

# 파일 인코딩 확인
def detect_encoding(file_path):
    with open(file_path, 'rb') as file:
        raw_data = file.read()
    return chardet.detect(raw_data)['encoding']

file_path = '/content/drive/MyDrive/20260114/(4th)3m_blandaltman1.csv'
detected_encoding = detect_encoding(file_path)

data = pd.read_csv(file_path, encoding=detected_encoding, header=0)
method1 = data.iloc[:, 0].values
method2 = data.iloc[:, 1].values

diff = method1 - method2
mean = (method1 + method2) / 2
md = np.mean(diff)
sd = np.std(diff, axis=0)
loa_upper = md + 1.96 * sd
loa_lower = md - 1.96 * sd

# --- 그래프 스타일 수정 ---
plt.rcParams['font.family'] = 'sans-serif'
# figsize를 줄여서 전체 그래프 크기 축소
fig, ax = plt.subplots(figsize=(5, 3))

# 산점도 (검정색 점)
ax.scatter(mean, diff, color='black', s=30, alpha=0.8, edgecolors='white', linewidth=0.5)

# 기준선들 (흑백 스타일)
ax.axhline(loa_upper, color='black', linestyle='--', linewidth=1)
ax.axhline(loa_lower, color='black', linestyle='--', linewidth=1)
ax.axhline(0, color='gray', linestyle='-', linewidth=0.5)

# X축 틱 설정 - 동일 간격
tick_values = [36, 36.5, 37, 37.5, 38]
ax.set_xticks(tick_values)
ax.set_xticklabels(['36', '36.5', '37', '37.5', '38'])
ax.set_xlim(35.5, 38.5)  # 여백 추가

# 축 레이블
ax.set_xlabel('Average', fontsize=12, fontweight='bold')
ax.set_ylabel('Difference', fontsize=12, fontweight='bold')

# Y축 범위 및 틱 설정
ax.set_ylim(-1.0, 1.0)
ax.set_yticks([-1.0, -0.5, 0.0, 0.5, 1.0])

# X축을 y=0 위치로 이동
ax.spines['bottom'].set_position(('data', 0))

# X축 spine의 범위를 38까지로 제한
ax.spines['bottom'].set_bounds(35.5, 38)

# 테두리 정리
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
ax.spines['left'].set_linewidth(1.2)
ax.spines['bottom'].set_linewidth(1.2)

# 수치 텍스트 추가 (그래프 우측)
x_max = ax.get_xlim()[1]
ax.text(x_max, loa_upper, f' {loa_upper:.2f}', va='center', ha='left', fontsize=10)
ax.text(x_max, loa_lower, f' {loa_lower:.2f}', va='center', ha='left', fontsize=10)

plt.tight_layout()
plt.show()

print(f"평균오차: {md:.2f}, 상한: {loa_upper:.2f}, 하한: {loa_lower:.2f}")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import chardet

# 파일 인코딩 확인
def detect_encoding(file_path):
    with open(file_path, 'rb') as file:
        raw_data = file.read()
    return chardet.detect(raw_data)['encoding']

# 파일 경로
file_path = '/content/drive/MyDrive/20241011/20241011_samsung_standard_coverless.csv'

# 인코딩 감지 및 출력
detected_encoding = detect_encoding(file_path)
print(f"Detected encoding: {detected_encoding}")

# CSV 파일 로드 (헤더를 첫 번째 행으로 지정)
data = pd.read_csv(file_path, encoding=detected_encoding, header=0)

# 열 이름 확인 및 데이터 추출
print("Column names:", data.columns)
method1 = data.iloc[:, 0].values
method2 = data.iloc[:, 1].values

# 차이와 평균 계산
diff = method1 - method2
mean = (method1 + method2) / 2

# 차이의 평균과 표준편차 계산
md = np.mean(diff)
sd = np.std(diff, axis=0)

# 일치도 한계 계산 (차이의 평균 ± 1.96 * 차이의 표준편차)
loa_upper = md + 1.96 * sd
loa_lower = md - 1.96 * sd

# Bland-Altman 플롯 그리기
fig, ax = plt.subplots(1, figsize=(10, 8))
ax.scatter(mean, diff, alpha=0.5)
ax.axhline(md, color='gray', linestyle='--', label='Mean difference')
ax.axhline(loa_upper, color='red', linestyle='--', label='Upper LOA')
ax.axhline(loa_lower, color='red', linestyle='--', label='Lower LOA')

ax.set_xlabel('Mean of two methods')
ax.set_ylabel('Difference between two methods')
ax.set_title("Bland-Altman_Samsung")

# y축 범위 및 눈금 설정
plt.ylim(-1.5, 0.7)
plt.yticks(np.arange(-1.5, 0.7, 0.1))

# y축 범위 및 눈금 설정
plt.xlim(36.5, 37.5)

# 선 레이블 추가
ax.text(ax.get_xlim()[1], md, f'{md:.2f}', va='center', ha='left', backgroundcolor='w')
ax.text(ax.get_xlim()[1], loa_upper, f'{loa_upper:.2f}', va='center', ha='left', backgroundcolor='w')
ax.text(ax.get_xlim()[1], loa_lower, f'{loa_lower:.2f}', va='center', ha='left', backgroundcolor='w')

ax.legend()
plt.tight_layout()
plt.show()

print(f"Bias: {md:.2f}")
print(f"LOA: {loa_upper - md:.2f}")